### ISSUE TITLE
opam config var share  --> opam var share

### ISSUE THREAD

**Issue by Sylvain78** [ocaml-opam/opam-user-setup#55]
In https://github.com/ocaml-opam/opam-user-setup/blob/master/vim/vim.ml#L130, "opam config var" is deprecated in favour of "opam var"

**Comment by pejato** [comment]
What's the status on this? Every time one runs `opam user-setup install`, ~10 lines of 
```
[WARNING] var was deprecated in version 2.1 of the opam CLI. Use opam var instead or set OPAMCLI environment variable to 2.0.
```
are logged.

This PR looks like it will resolve the warnings, can it be merged @rjbou?
https://github.com/ocaml-opam/opam-user-setup/pull/52

**Comment by kit-ty-kate** [comment]
#52 was merged and released in https://github.com/ocaml/opam-repository/pull/26480. Sorry for the delay
